### ISSUE TITLE
Error on docker compose

### ISSUE THREAD

**Issue by JoseVacas** [shouya/rss-funnel#101]
Hi.
When a lunch docker compose up with the example docker-compose.yaml
```yml
version: "3.8"
services:
  rss-funnel:
    image: ghcr.io/shouya/rss-funnel:latest
    ports:
      - 4080:4080
    volumes:
      - ./funnel.yaml:/funnel.yaml
    environment:
      RSS_FUNNEL_CONFIG: /funnel.yaml
      RSS_FUNNEL_BIND: 0.0.0.0:4080
```

 ✔ Network rss-funnel_default         Created                                                               0.1s 
 ✔ Container rss-funnel-rss-funnel-1  Created                                                               0.0s 
Attaching to rss-funnel-1
rss-funnel-1  | Error: Config(Yaml(Error("Is a directory (os error 21)")))
rss-funnel-1 exited with code 1

I get this error.
Whats can I do?
