### ISSUE TITLE
Enable `full_text:` to Utilize `user_agent:` Configuration

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#114]
In the current nightly version, the configuration `full_text: {}` does not appear to utilize the specified `user_agent:` setting.

```yaml
  - path: /aninews-health.xml
    source: https://aninews.in/rss/feed/category/health.xml
    client:
      timeout: '10s'
      user_agent: 'Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0'
    filters:
      - limit: 1
      - full_text: {}
      - simplify_html: {}
      - modify_post: post.link = post.link.replace("http://", "https://")
```
