### ISSUE TITLE
Error when `source` URL is not encoded

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#136]
I encountered an issue if the `?source=` URL is not URL-encoded in the configuration. Below is the current configuration causing the error:

```
  - path: /manjultoons.xml
    source: /image-proxy.xml?source=https://bridge.easter.fr/?action=display&bridge=TelegramBridge&username=MANJULtoons&format=Atom
    filters:
      - keep_only:
          field: title
          matches: '#cartoon'
          case_sensitive: true
```

Also, could you change the `keep_only on-the-fly` rule to use 'title' as the default match?
