### ISSUE TITLE
Handling Errors Gracefully

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#143]
Currently, RSS-Funnel fails with the error `Reqwest client error: error sending request for url (https://bridge.easter.fer/?action=display&bridge=FirefoxReleaseNotesBridge&platform=beta&format=Atom)` if one of the requested feeds encounters an error. This causes the entire operation to break, which is not ideal.

**Proposal:**

Instead of completely breaking the entire process when a single feed fails, I propose showing a warning while continuing to process the remaining feeds. In most cases, if a single feed error affects the entire operation, it's not the best practice. The RSS-Funnel should continue generating the feeds and log or display error messages for the failed requests.

**Example Configuration:**

```yaml
  - path: /firefox-releases.xml
    source:
      format: atom
      title: Firefox Releases
      link: https://www.mozilla.org/en-US/firefox/
    filters:
      - merge:
          - https://bridge.easter.fr/?action=display&bridge=FirefoxReleaseNotesBridge&platform=&format=Atom
          - https://bridge.easter.fr/?action=display&bridge=FirefoxReleaseNotesBridge&platform=android&format=Atom
          - https://bridge.easter.fr/?action=display&bridge=FirefoxReleaseNotesBridge&platform=nightly&format=Atom
          - https://bridge.easter.fer/?action=display&bridge=FirefoxReleaseNotesBridge&platform=beta&format=Atom
      - modify_post: |
          post.title.value = post.title.value.replace("Release Note", "");
```

By implementing this change, RSS-Funnel will be more resilient and able to handle individual feed errors gracefully without impacting the entire feed generation process.
