### ISSUE TITLE
On-the-Fly and Placeholder Filters Fail When `keep_only` or `discard` Are Configured

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#144]
When the `keep_only` or `discard` options are set in the configuration, the On-the-Fly and Placeholder filters fail, resulting in no feeds being returned.

```
  - path: /otf
    on_the_fly_filters: true
    filters:
      - keep_only:
          field: title
```

Could you tell me where to modify the code so that the keep_only and discard filters are applied to the title by default? Many YouTube feeds have descriptions with keywords that I don't want to filter, which often leads to false positives. To overcome this, I primarily use these filters to target titles only, so I will compile the code myself after making the changes.
