### ISSUE TITLE
error fetching full text: HTTP status error 403 Forbidden

### ISSUE THREAD

**Issue by MrCaringi** [shouya/rss-funnel#145]
Hi,
for some feeds, I am getting this kind of errors in every item in the feed:

```
error fetching full text: HTTP status error 403 Forbidden (url: https://lat.motorsport.com/f1/news/hamilton-interes-motogp-equipo-liberty/10653282/?utm_source=RSS&utm_medium=referral&utm_campaign=RSS-MOTOGP&utm_term=News&utm_content=lat)
```

this is my current config file `funnel.yml`:
```yml
endpoints:
  - path: /full-text.xml
    note: Full text of any Source
    filters:
      - full_text: {}
      - simplify_html: {}
```

feed: `https://lat.motorsport.com/rss/motogp/news/`

this instance is installed in `Ubuntu 22.04.4 LTS aarch64`, with `docker compose`

Screenshot:

![2024-09-11 19 52 50](https://github.com/user-attachments/assets/0dea4ff2-a57b-4997-99e6-c9ee98544ec0)

Thanks in advance for your support!

**Comment by shouya** [comment]
Apparently the webpage blocks non-browser requests. Compare the output of:

```
$ curl -I -H 'user-agent: random' 'https://lat.motorsport.com/f1/news/hamilton-interes-motogp-equipo-liberty/10653282/?utm_source=RSS&utm_medium=referral&utm_campaign=RSS-MOTOGP&utm_term=News&utm_content=lat'
HTTP/2 403
...
```

and 

```
$ curl -I -H 'user-agent: Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0' 'https://lat.motorsport.com/f1/news/hamilton-interes-motogp-equipo-liberty/10653282/?utm_source=RSS&utm_medium=referral&utm_campaign=RSS-MOTOGP&utm_term=News&utm_content=lat'
HTTP/2 200
...
```

So it should be possible to get around the block by setting `full_text.client.user_agent` to a browser user-agent. The resulting config should look like this:

```yaml
endpoints:
  - path: /full-text.xml
    note: Full text of any Source
    filters:
      - full_text:
          client:
            user_agent: "Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0"
      - simplify_html: {}
```

**Comment by MrCaringi** [comment]
thanks a lot!!!!
let my try it

**Comment by MrCaringi** [comment]
I updated my `funnel.yml` config file, now it looks like this:
```yml
endpoints:
  - path: /full-text.xml
    note: Full text of any Source
    filters:
      - full_text: {}
      - simplify_html: {}

  - path: /agent.xml
    note: Full with user-agent
    filters:
      - full_text:
          client:
            user_agent: "Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0"
      - simplify_html: {}
```

When I applied this new config, I got this error:

```shell
rss-funnel-1 exited with code 1
rss-funnel-1  | 2024-09-13T01:47:13.616608Z  INFO rss_funnel::server: loading config from "/funnel.yaml"
rss-funnel-1  | Error: Config(Yaml(Error("endpoints[1]: missing field `timeout`", line: 8, column: 5)))
```

So, I was looking for this parameter in your repository, and found this: 
https://github.com/shouya/rss-funnel/blob/29141c5c351f21031fb12c0b0704840076f6f3cd/src/client.rs#L53

So, I try this config (I added the `timeout` parameter):

```yml
endpoints:
  - path: /full-text.xml
    note: Full text of any Source
    filters:
      - full_text: {}
      - simplify_html: {}

  - path: /agent.xml
    note: Full with user-agent
    timeout: 2m
    filters:
      - full_text:
          client:
            user_agent: "Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0"
      - simplify_html: {}
```

But this didnt make the trick, I have the same error:

```shell
[+] Running 2/2
 ✔ Network dc-rss-funnel_default  Created                                                                                                                                                              0.1s 
 ✔ Container rss-funnel           Started                                                                                                                                                              0.3s 
rss-funnel exited with code 1
rss-funnel  | 2024-09-13T01:53:14.248547Z  INFO rss_funnel::server: loading config from "/funnel.yaml"
rss-funnel  | Error: Config(Yaml(Error("endpoints[1]: missing field `timeout`", line: 8, column: 5)))
```

Any idea what I am doing wrong?
