### ISSUE TITLE
Allow creating new feed from scratch

### ISSUE THREAD

**Issue by shouya** [shouya/rss-funnel#35]
This would be helpful in cases where you want to merge a lot of feeds together. Then you can just make a new feed as:

```
- path: /my-lovely-feed.xml
  source:
    from_scratch:
      title: My Lovely Feed Aggregation
      link: http://not-available.com
  filters:
    - merge: http://feed1.xml
    - merge: http://feed2.xml
```
