### ISSUE TITLE
Allow calling existing endpoints recursively

### ISSUE THREAD

**Issue by shouya** [shouya/rss-funnel#36]
Now if we want to refer to an endpoint inside another endpoint (e.g. in `merge` filter), we have to write out the absolute url explicitly.

```
- path: /generate.xml
  filters: <some filters>
- path: /my-feed.xml
  source: <some source feed>
  filters:
    - merge: http://my-domain/generate.xml?source=https://source1/page.html
    - merge: http://my-domain/generate.xml?source=https://source2/page.html
    - merge: http://my-domain/generate.xml?source=https://source3/page.html
```

It would be nice if we can omit that like this:

```
- path: /generate.xml
  filters: <some filters>
- path: /my-feed.xml
  source: <some source feed>
  filters:
    - merge: /generate.xml?source=https://source1/page.html
    - merge: /generate.xml?source=https://source2/page.html
    - merge: /generate.xml?source=https://source3/page.html
```

It would be better if we can detect cycles and stops the infinite chain. But this shouldn't be much of an issue given the timeout setting is there to avoid leaking.

The host name can be either inferred from `Host` field or have it converted into an internal call.
