### ISSUE TITLE
A less verbose js_filter

### ISSUE THREAD

**Issue by shouya** [shouya/rss-funnel#38]
Currently, in bare minimum, one need to write something like:

```js
          function modify_post(feed, post) {
            return post;
          }
```

to make the js filter work. Any modification made to `post` needs to be assigned back and returned. This is quite cumbersome and prone to mistake. Also in reality, I expect most modification to be small and perhaps many can be done in one or two lines. It would be nice to have a shorter syntax for short js code.

I'm considering syntax like this:

```yaml
filters:
  - modify_post: post.title = `${post.title} - ${feed.title}`
  - modify_feed: feed.items = feed.items.slice(0, 5)
```
