### ISSUE TITLE
Merge multiple sources in one filter

### ISSUE THREAD

**Issue by shouya** [shouya/rss-funnel#45]
Add support for multiple sources in the same `merge` filter that looks like:

```yaml
- path: /my-feed.xml
  source: <some source feed>
  filters:
    - merge:
      - http://my-domain/generate.xml?source=https://source1/page.html
      - http://my-domain/generate.xml?source=https://source2/page.html
      - http://my-domain/generate.xml?source=https://source3/page.html
```

which is (mostly) equivalent to:

```yaml
- path: /my-feed.xml
  source: <some source feed>
  filters:
    - merge: http://my-domain/generate.xml?source=https://source1/page.html
    - merge: http://my-domain/generate.xml?source=https://source2/page.html
    - merge: http://my-domain/generate.xml?source=https://source3/page.html
```

As well as the syntax like this:

```yaml
- path: /my-feed.xml
  source: <some source feed>
  filters:
    - merge:
        client: <client config>
        filters: <filters to run on each merged feed>
        source:
          - http://my-domain/generate.xml?source=https://source1/page.html
          - http://my-domain/generate.xml?source=https://source2/page.html
          - http://my-domain/generate.xml?source=https://source3/page.html
```

This would be helpful in speeding up the fetch. If we have multiple merges, we have to execute each one in sequence, but inside one `merge` filter we parallelize the fetch.
