### ISSUE TITLE
Personalize Name and Image in RSS Feeds from Multiple Sources

### ISSUE THREAD

**Issue by uGeek** [shouya/rss-funnel#59]
When creating an RSS feed from multiple sources, it always adopts the name and image of the first feed. Could an option be added to specify the name of the new generated feed and the image to avoid confusion?

**Comment by shouya** [comment]
It may be impossible to do because the image and name of feed is a property of the feed, not the items.

An alternative is to add the feed's name as part of the title for each item:

```yaml
- filters:
  - merge:
      source: http://example.com/feed1.xml
      filters:
        - js: |
            function modify_post(feed, post) {
              post.title += ` - ${feed.title}`;
              return post;
            }
  - merge:
      source: http://example.com/feed2.xml
      filters:
        - js: |
            function modify_post(feed, post) {
              post.title += ` - ${feed.title}`;
              return post;
            }
  - merge:
      source: http://example.com/feed3.xml
      filters:
        - js: |
            function modify_post(feed, post) {
              post.title += ` - ${feed.title}`;
              return post;
            }
  - merge:
      source: http://example.com/feed4.xml
      filters:
        - js: |
            function modify_post(feed, post) {
              post.title += ` - ${feed.title}`;
              return post;
            }
```

The merge filter in the latest release (0.0.5) doesn't support multiple source yet. But if you compile the latest master or wait for the next release, the config can be simplified further to just:

```yaml
- filters:
  - merge:
      source:
        - http://example.com/feed1.xml
        - http://example.com/feed2.xml
        - http://example.com/feed3.xml
        - http://example.com/feed4.xml
      filters:
        - modify_post: post.title += ` - ${feed.title}`;
```

**Comment by shouya** [comment]
I realized I may have misinterpreted your suggestion.

> Could an option be added to specify the name of the new generated feed and the image to avoid confusion?

If you're talking about whether we can start the feed from not one of the source but instead a blank feed from scratch, the answer is yes! See https://github.com/shouya/rss-funnel/issues/35 and https://github.com/shouya/rss-funnel/pull/44.

There is no support for setting image in the scratch feed yet. But you can do it easily with a `modify_feed` filter:

```yaml
- path: /feed.xml
  source:
    format: rss # or atom
    title: "My Feed"
    description: "This is my feed"
    link: "https://example.com/"
  filters:
    - merge:
      - https://example.com/feed1.xml
      - https://example.com/feed2.xml
      - https://example.com/feed3.xml
    - modify_feed: |
      feed.image = {
        url: "https://example.com/image.png",
        title: "My Feed",
        link: "https://example.com/"
      }
    
```
