### ISSUE TITLE
Problems with `discard`

### ISSUE THREAD

**Issue by ctechols** [shouya/rss-funnel#78]
Based on https://github.com/shouya/rss-funnel/wiki/Filter-config#keep_only--discard, I'd expect this yaml to be valid configuration:

```
  - path: /app-sales.xml
    source: https://www.app-sales.net/highlights/
    note: App Sales Highlights
    filters:
      - split:
          title_selector: ".sale-list-item p.app-name"
          link_selector: ".sale-list-item .sale-list-action > a"
          description_selector: ".sale-list-item .pricing"
      - discard: field: title contains:
        - 'icon pack'
        - 'watch face'
        case_sensitive: false
```

However, I get the following error on startup:

```
rssfunnel-1  | Error: Config(Yaml(Error { kind: SCANNER, problem: "mapping values are not allowed in this context", pro
blem_mark: Mark { line: 36, column: 23 } }))
```

(The line number above references my entire config.  line 36 corresponds to the `discard` key in the above snippet).

If I change the config to this:
```
  - path: /app-sales.xml
    source: https://www.app-sales.net/highlights/
    note: App Sales Highlights
    filters:
      - split:
          title_selector: ".sale-list-item p.app-name"
          link_selector: ".sale-list-item .sale-list-action > a"
          description_selector: ".sale-list-item .pricing"
      - discard:
        - 'icon pack'
        - 'watch face'
```

`rss_funnel` will start up without error and the `discard` configuration will show up for this endpoint within the inspector.  However, I'm still seeing entries in the rss output that I would have expected to be discarded.  (Specifically ones with "Icon Pack" in the title).

**Comment by shouya** [comment]
> `      - discard: field: title contains:`

This is an typesetting error. I have fixed it in the documentation,

```
      - discard:
        - 'icon pack'
        - 'watch face'
```

The reason your config didn't match it is because of a bug where the keywords are treated as case sensitive. I will fix it soon in 0.1.1.

For the time being, you can either specify the casing of the patterns to match the feed, i.e..:

```yaml
  - path: /app-sales.xml
    source: https://www.app-sales.net/highlights/
    note: App Sales Highlights
    filters:
      - split:
          title_selector: ".sale-list-item p.app-name"
          link_selector: ".sale-list-item .sale-list-action > a"
          description_selector: ".sale-list-item .pricing"
      - discard:
          - "Icon Pack"
          - "Watch Face"
```

Or explicitly specify `case_sensitive` field to `false`, i.e.:

```yaml
  - path: /app-sales.xml
    source: https://www.app-sales.net/highlights/
    note: App Sales Highlights
    filters:
      - split:
          title_selector: ".sale-list-item p.app-name"
          link_selector: ".sale-list-item .sale-list-action > a"
          description_selector: ".sale-list-item .pricing"
      - discard:
          case_sensitive: false
          matches:
            - "icon pack"
            - "watch face"
```
