### ISSUE TITLE
Limit number of posts

### ISSUE THREAD

**Issue by uGeek** [shouya/rss-funnel#8]
Is there a possibility of reducing the number of posts in the original feed? Adding it in the Filters section?

**Comment by shouya** [comment]
Yes, you can use a JS filter on `feed`:

``` yaml
  - path: /hn-first-5.xml
    source: https://news.ycombinator.com/rss
    filters:
      - js: |
          function modify_feed(feed) {
            feed.items = feed.items.slice(0, 5);
            return feed;
          }
```


May I ask what your real-life use case is? I may implement a standalone filter for this feature if it's suited for general use cases.
