### ISSUE TITLE
RSS_FUNNEL_WATCH=true is unreliable

### ISSUE THREAD

**Issue by ctechols** [shouya/rss-funnel#80]
I'm running `rss_funnel` via a docker compose file with the `RSS_FUNNEL_WATCH: true` inside the `environment:` block.

I startup `rss_funnel` with a valid `funnel.yaml` file and appropriate `RSS_FUNNEL_CONFIG` environment setting.  The logs report:
```
rssfunnel-1  | 2024-03-12T14:35:04.534164Z  INFO rss_funnel::server: watching config file for changes
...<snipped for brevity>...
rssfunnel-1  | 2024-03-12T14:35:04.674727Z  INFO rss_funnel::server: starting server
```

Then I edit my `funnel.yaml` to completely remove one of the endpoints.  The logs then report:
```
rssfunnel-1  | 2024-03-12T14:42:14.539908Z  INFO rss_funnel::server: config updated, reloading service
```

After that I go to my browser, reload the inspector page and also click the "Reload Config" button.  I would expect the endpoint I just deleted to be absent from the inspector UI, but it is still present.

I can *mostly* get the logs to report a successful reload if I change a config from invalid to valid.  However even then it doesn't appear to always work.  (Sorry I don't have more concrete reproduction steps).

**Comment by shouya** [comment]
That is weird. I attempted to reproduce it without success. I tried adding and removing endpoints, each of the change is successfully picked up by the file system watcher and the ui after pressing the "Reload Config" button.

I'm suspecting maybe it's the inotify event are not passing through docker mount boundary. On my development environment I run the binary directly without docker, and in my docker deployed node I don't use the watch feature.

Can you give me your `docker-compose.yaml`? I'll see if I can reproduce it with the exact config.

**Comment by ctechols** [comment]
This minimal `docker-compose.yml` reproduces the issue for me:
```
version: '3.7'

services:
  rssfunnel:
    image: "ghcr.io/shouya/rss-funnel:0.1.0"
    restart: unless-stopped
    volumes:
      - ./funnel.yaml:/funnel.yaml
    ports:
      - 4081:4081
    environment:
      RSS_FUNNEL_CONFIG: /funnel.yaml
      RSS_FUNNEL_BIND: 0.0.0.0:4081
      RSS_FUNNEL_WATCH: true
```
