### ISSUE TITLE
Empty Content and Parsing Error When Aggregating YouTube Channels

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#86]
Thank you for the software.

I attempted to aggregate content from multiple YouTube channels using the provided code. However, upon inspection in the UI, it appears that there is no rendered content, although RAW and JSON data can be generated successfully.

When using the feed reader [Yarr](https://github.com/nkanaev/yarr), only the content is empty. Additionally, when trying with the WebExtension [rsspreview](https://addons.mozilla.org/en-US/firefox/addon/rsspreview/) to preview RSS feeds in the browser, it throws an error `XML Parsing Error: prefix not bound to a namespace`.

```
endpoints:
  - path: /youtube.xml
    source:
      format: atom
      title: YouTube
      link: https://www.youtube.com
      description: Aggregate content from multiple YouTube channels and exclude YouTube shorts
    filters:
      - merge:
          filters:
            - discard:
              - shorts
          source:
            - https://www.youtube.com/feeds/videos.xml?channel_id=UCiPmhfdCL06cSVTXKabF0Zg
            - https://www.youtube.com/feeds/videos.xml?channel_id=UCueYcgdqos0_PzNOq81zAFg
```
![Screenshot 2024-03-16 at 09-34-54 RSS Funnel Inspector](https://github.com/shouya/rss-funnel/assets/19629778/0960e4b7-2db0-4b4f-9833-859e55a9bc47)
![Screenshot 2024-03-16 at 09-35-09 RSS Funnel Inspector](https://github.com/shouya/rss-funnel/assets/19629778/9c77a933-709e-4ce0-8573-806e33ebf09d)
![Screenshot_20240316_093609](https://github.com/shouya/rss-funnel/assets/19629778/05d74238-f77a-44ff-a1d0-d4874ed981a9)
