### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#87]
An error occurs when trying to use the attribute in the configuration of the RSS funnel, as documented in the wiki.

**Error 1:**

```
Error: Config(Yaml(Error("endpoints[0]: data did not match any variant of untagged enum SourceConfig", line: 2, column: 5)))
```

```
endpoints:
  - path: /youtube.xml
    source:
      from_scratch:
        format: atom
        title: YouTube
        link: https://www.youtube.com
        description: Aggregate content from multiple YouTube channels and exclude YouTube shorts
    filters:
      - merge:
          filters:
            - discard:
              - shorts
          source:
            - https://www.youtube.com/feeds/videos.xml?channel_id=UCiPmhfdCL06cSVTXKabF0Zg
            - https://www.youtube.com/feeds/videos.xml?channel_id=UCueYcgdqos0_PzNOq81zAFg
```

**Error 2:**

```
Error: Config(Yaml(Error("endpoints[0]: data did not match any variant of untagged enum MergeConfig", line: 2, column: 5)))
```

```
endpoints:
  - path: /youtube.xml
    source:
      format: atom
      title: YouTube
      link: https://www.youtube.com
      description: Aggregate content from multiple YouTube channels and exclude YouTube shorts
    filters:
      - merge:
          filters:
            - discard:
              field: title
              matches:
                - shorts
          source:
            - https://www.youtube.com/feeds/videos.xml?channel_id=UCiPmhfdCL06cSVTXKabF0Zg
            - https://www.youtube.com/feeds/videos.xml?channel_id=UCueYcgdqos0_PzNOq81zAFg
```

I have the ability to edit the wiki without requiring permission, but I am unable to revert changes. Could you please verify this as well? Thank you.

**Comment by shouya** [comment]
The source doesn't accept a `from_scratch` key, so the source should look like:

```yaml
    source:
      format: atom
      title: YouTube
      link: https://www.youtube.com
      description: Aggregate content from multiple YouTube channels and exclude YouTube shorts
```

Also, you need to indent the fields beneath `discard` filter as follows:

```yaml
          filters:
            - discard:
                field: title
                matches:
                  - shorts
```

In fact, your config in https://github.com/shouya/rss-funnel/issues/86 is fine. Let me check what went wrong with the processing.

I'm closing this issue because the config is indeed invalid. Feel free to reopen if you disagree.

-------

> I have the ability to edit the wiki without requiring permission, but I am unable to revert changes.

I saw you have already reverted the change. Don't worry. I have corrected the wrong description on using "from scratch" source from the wiki :)
