### ISSUE TITLE
Feature Request: Option to Limit Number of Feeds

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#88]
Some websites provide hundreds of feeds, so utilizing `full_text` causes excessive load. There's a concern about potential rate limiting and IP address bans due to the increased feed generation.

**Comment by shouya** [comment]
What do you mean by limiting the number of feeds? Do you mean to limit the number of articles/posts/items?

If that's what you want you can use the `modify_feed` filter as follows:

```yaml
- path: /my-full-text-feed.xml
  source: https://example.com/feed.xml
  filters:
    # if the feed's format is rss:
    - modify_feed: feed.items = feed.items.slice(0, 10);
    # or if the feed's format is atom:
    # - modify_feed: feed.entries = feed.entries.slice(0, 10);
    - full_text: {}
```

Change the number `10` to the number of articles/posts/items you want to keep.
