### ISSUE TITLE
Feature Request: Simplified Feed Filtering with Expanded Query Parameter Support

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#93]
Currently, if I want to remove short videos from a YouTube channel feed and do not want to merge, I have to write specific code for each individual feed. This process seems inefficient. Instead of this, I suggest allowing the use of `?url=` in the query parameter for the source field. 

For instance, instead of:

```
  - path: /youtube-kurzgesagt.xml
    source: https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q
    filters:
      - discard:
          field: title
          matches: shorts
```

We could have a more generic endpoint like:

```
  - path: /remove-shorts.xml
    filters:
      - discard:
          field: title
          matches: shorts
```

Then, we could utilize the `?url=` parameter and call it to perform an action on the feed URL, like so:

```
http://127.0.0.1:4080/remove-shorts.xml?url=https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q
```

This would streamline the process.
