### ISSUE TITLE
Help is needed as `remove_regex` is not working as expected

### ISSUE THREAD

**Issue by tillcash** [shouya/rss-funnel#95]
Could you please assist me? I'm attempting to remove some text, but it's not functioning as anticipated.

source: https://www.thenewsminute.com/api/v1/collections/tamil-nadu.rss

```
  - path: /newsminute.xml
    filters:
      - sanitize:
          - remove_regex: '<p><strong>Read.*?<\/strong><\/p>'
```

![image](https://github.com/shouya/rss-funnel/assets/19629778/a07154a4-0cca-4c41-a544-837719c322f1)
